FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN --mount=type=cache,target=/root/.cache,sharing=shared \
    pip install --upgrade pip && \
    pip install uv && \
    uv pip install --system --no-cache-dir -r requirements-kick.txt